---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: local/consumer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: bitnami-kafka:9092
      restartPolicy: Always