---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: kafka
  name: kafka-job
  namespace: streaming
spec:
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: local/kafka:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: bitnami-kafka:9092
      restartPolicy: Never