apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: kafka
  name: kafka-job
  namespace: streaming
spec:
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -zv bitnami-kafka 9092; do echo "Waiting for Kafka"; sleep 2; done; echo "Kafka is ready!";']
      containers:
      - name: kafka
        image: local/kafka:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: bitnami-kafka:9092
        - name: KAFKA_SECURITY_PROTOCOL
          value: "PLAINTEXT"
      restartPolicy: Never